### ISSUE TITLE
[FEATURE] no more error when deploy already running

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/enac-cd-app#9]
# What we currently have
** When deploying multiple time (several github actions running on the same time)
 - the first time we have a job_id
 - the second time we have an error because it's already running

It's making it not obvious in the CD that the deployment was successful.

# What I wish we had

** When deploying multiple time (several github actions running on the same time)
 - the first time we have a job_id
 - the second time we have the same job_id a status="running" because it's already running
 - We don't have a status=error, we may have an additional information regarding the fact that it was running before (timestamp or something else

That way, we will only see 'real failure' in the github actions pipelines. Instead of having 'failed deploy prod' which is not the case.

**Comment by sbancal** [comment]
Implemented in a58c54527cd2e512d53f5fb577608fb2f99552ce
but requires new behavior.

- [x] Don't consume output, as it might be read by several GH Actions at the same time: a0df985361940d9081aa23455c0f25a1fe93e210
- [x] Since output is not consumed anymore, we must print only what was not already displayed: https://github.com/EPFL-ENAC/epfl-enac-deploy-action/issues/9
- [x] As the process after git clone is the longest and can take several minutes, we must include the SHA1 of the deployed commit in the output: https://github.com/EPFL-ENAC/enacit-ansible/issues/127

**Comment by sbancal** [comment]
This is now implemented.

BTW, there is this https://github.com/EPFL-ENAC/epfl-enac-deploy-action/discussions/11 that talks about evolution of this feature.
